### ISSUE TITLE
When Activity is resumed, Marker moving to Current Location

### ISSUE THREAD

**Issue by SrikanthReddyRamidi** [Sishin/MapLocation#2]
When i moved the location and  went to another activity. When i come back, the marker position is moved to My Location. How to make marker location to remain unchanged.

**Comment by Sishin** [comment]
You can handle it in Onresume by saving the previously selected location in a sharedpref

**Comment by SrikanthReddyRamidi** [comment]
I have created a variable  isChangeMapMethodCalled and by default it is false. It is made true in ChangeMap method. 

In onConnected Method below line 
`if (mLastLocation != null)`
is changed to 
`if (mLastLocation != null && isChangeMapMethodCalled == false) `

In onLocationChanged Method below line 
`if (location != null)`
is changed to 
`if (location != null && isChangeMapMethodCalled == false)`

Problem got fixed.
